package app

// A Chat represents a history of conversations between multiple users.
type Chat struct {
	ID      string // autogenerated by db
	Name    string
	GroupID string // id of group this chat belongs to
}
