package app

// A Group represents a collection of user and chats.
type Group struct {
	ID      string `json:"id"` // autogenerated by db
	Name    string `json:"name"`
	AdminID string `json:"adminId"` // id of group admin user
	IconID  string `json:"iconId"`  // id of icon image
}

// GetGroupChats gets the all the chats the belong to this group.
func (g *Group) GetGroupChats() []Chat {
	chats := make([]Chat, 0)
	return chats
}
